### ISSUE TITLE
Error should be in JSON format

### ISSUE THREAD

**Issue by beshkenadze** [4xxi/caesarapp-server#5]

**Comment by rqrqrqrq** [comment]
To clarify this issue, validation errors have status 400 and follow this structure:
```json
{
  "errors": [
    "message - This value should not be blank.",
    "passphrase - smth"
  ]
}
``` 
I think its not as useful as 
```js
{
  "errors": [
    { 
      "fieldname": string, 
      "errortext": string 
    },
   ...
 ]
}
```
or something like that. With this client app should not parse and split error messages to know what happens.

Another good solution is provide array of human-readable errors so client can show them directly.

---

I guess mainly this issue related to 404 and 500 errors. Now server responds with html page even if header `'X-Requested-With': 'XMLHttpRequest'` has been set.

**Comment by beshkenadze** [comment]
Done in ba91bcad4cb8656a06d69e603dca1240a42f472e
