### ISSUE TITLE
Remove "message - This value should not be blank." error when user wants to share only files

### ISSUE THREAD

**Issue by rqrqrqrq** [4xxi/caesarapp-server#6]
Unnecessary server validation forces user to leave message (and even whitespace fails) when he wants to share file. IMHO this is UX problem.

Suggestion: we should throw error only when there is no stuff to share — no files and no text. So we can always validate this on frontend, server-side validation is just the second gates.

branch: master

**Comment by amilaev** [comment]
Backend validation is implemented.
